initializing project
WildCodeSchool/0523-RemFr-JavaAngular-P2-backend-brainwave pull request #2
Opened 2023-07-05 14:51 UTC by AntoineMtbn

2023-07-05 14:51 UTC, SoBanzail approved these changes

2023-07-05 14:52 UTC, Heleneb1 approved these changes

2023-07-05 15:07 UTC, bastienapp requested changes

2023-07-05 15:07 UTC, bastienapp commented on src/main/java/com/templateproject/api/entity/Event.java
> +    @JoinColumn(name = "user_id")
faire un `@JoinTable`, voir la quête ou une de mes vidéos

2023-07-05 15:07 UTC, bastienapp commented on src/main/java/com/templateproject/api/entity/Promotion.java
> +    private Float note;
rate ou rating

2023-07-05 15:07 UTC, bastienapp commented on src/main/java/com/templateproject/api/entity/Promotion.java
> +    private LocalDateTime creation_date;
camelCase

2023-07-05 15:07 UTC, bastienapp commented on src/main/java/com/templateproject/api/entity/Promotion.java
> +    private User user;
author

2023-07-05 15:07 UTC, bastienapp commented on src/main/java/com/templateproject/api/entity/Promotion.java
> +    private List<User> users;
nommer autrement (par exemple : participants)

2023-07-05 15:07 UTC, bastienapp commented on src/main/java/com/templateproject/api/entity/Resource.java
> +    private String content;
`@Lob` à ajouter pour les textes long (équivalent du type TEXT en SQL)

2023-07-05 15:07 UTC, bastienapp commented on src/main/java/com/templateproject/api/entity/Role.java
> +    admin,
par convention, les valeurs des enums sont en majuscule

2023-07-05 15:07 UTC, bastienapp commented on src/main/java/com/templateproject/api/entity/Topic.java
> +    private User user;
author

2023-07-05 15:07 UTC, bastienapp commented on src/main/java/com/templateproject/api/entity/User.java
> +    private List<Event> events;
eventsCreated

2023-07-05 15:07 UTC, bastienapp commented on src/main/java/com/templateproject/api/entity/Event.java
> +    private User user;
author

2023-07-05 15:07 UTC, bastienapp commented on src/main/java/com/templateproject/api/entity/Event.java
> +    private List<User> users;
participants

2023-07-05 15:07 UTC, bastienapp commented on src/main/java/com/templateproject/api/entity/User.java
> +
@OneToMany(mappedBy = "participants")
    private List<Event> eventsParticipated;

2023-07-05 15:07 UTC, bastienapp commented on src/main/java/com/templateproject/api/entity/User.java
> +    @OneToMany(mappedBy = "user")
mappedBy = "author"

2023-07-05 15:07 UTC, bastienapp commented on src/main/java/com/templateproject/api/repository/AnswerRepository.java
> +
`@Repository` dans tous les repos

2023-07-05 15:34 UTC, bastienapp requested changes

2023-07-05 15:34 UTC, bastienapp commented on src/main/java/com/templateproject/api/entity/Promotion.java
> +    @JoinColumn(name = "user_id")
à corriger

2023-07-06 06:58 UTC, bastienapp approved these changes
Validé :+1:

2023-07-06 07:30 UTC, merged