Feat/security
WildCodeSchool/0523-RemFr-JavaAngular-P2-backend-brainwave pull request #9
Opened 2023-07-18 14:26 UTC by maxime-auneau

2023-07-18 15:22 UTC, AntoineMtbn approved these changes

2023-07-19 09:41 UTC, Heleneb1 approved these changes

2023-07-19 09:59 UTC, bastienapp requested changes

2023-07-19 09:59 UTC, bastienapp commented on src/main/java/com/templateproject/api/controller/AuthenticationController.java
> +@CrossOrigin(origins = "localhost:4200")
`@CrossOrigin` peut être retiré

2023-07-19 09:59 UTC, bastienapp commented on src/main/java/com/templateproject/api/controller/AuthenticationController.java
> +            @Qualifier("authenticationManager") AuthenticationManager authManagerInjected,
Je ne pense pas que le `@Qualifier` soit nécessaire

2023-07-19 09:59 UTC, bastienapp commented on src/main/java/com/templateproject/api/controller/DemoController.java
> +@CrossOrigin("*")
`@CrossOrigin` peut être retiré

2023-07-19 09:59 UTC, bastienapp commented on src/main/java/com/templateproject/api/controller/UserController.java
> +@CrossOrigin(origins = "localhost:4200", allowCredentials = "true")
`@CrossOrigin` peut être retiré

2023-07-19 09:59 UTC, bastienapp commented on src/main/resources/application.properties
> +spring.h2.console.enabled=true
les lignes 35 à 38 sont à supprimer

2023-07-19 10:11 UTC, bastienapp approved these changes
Correction validées :+1:

2023-07-19 10:15 UTC, merged